### ISSUE TITLE
Request for a new release

### ISSUE THREAD

**Issue by manjunjiao** [redradrat/terraform-provider-kable#5]

**Comment by manjunjiao** [comment]
Can we have a new release pointing to the latest changes made to Kable repo pls?

**Comment by redradrat** [comment]
Released https://github.com/redradrat/terraform-provider-kable/releases/tag/v0.0.4

**Comment by redradrat** [comment]
actually 0.0.4 does not yet contain the new kable reference... I'll need to check possible dependency clashes. Sorry.

**Comment by redradrat** [comment]
v0.0.5 will use the new kable version 0.8.6.
